About:
  profile:
    name: "Vu Quang Minh"
    description: |
      🔨 Build Apps
      🌈 Spread Positive Vibes
      🤩 Do What Excites
    email: "minhvuquang2000317@gmail.com"
    phone: "+65 8742 9618"
  social:
    github: "https://github.com/Dev317"
    linkedin: "https://www.linkedin.com/in/vu-quang-minh-b0b41b207/"
    medium: "https://medium.com/@vuquangminh"
    instagram: "https://www.instagram.com/_n1xxy__/"
    facebook : "https://www.facebook.com/minh.vuquang.1238"
  summary:
    description: |
      - Currently an undergraduate pursuing Computer Science and Business courses.
      - Having strong interest in the development and employment of software applications/products that are scale-able, viable and most importantly, beneficial to society.
      - Participating in multiple hands-on projects in areas of software collaborative development, data analytics and market research to become a skilled and competent individual and to be able to work in different fields.
      - Seeking tech-related opportunities in Singapore or in Southeast Asia region to increase my exposure to the usage and deployment of tech-based applications across different industries!
  education:
    - "exchange":
      school: "**University of Edinburgh** (Exchange Semester)"
      year: "Aug 2023 - Jan 2024"
      degree: "*Informatics*"
      description: |
        - Deep dive in using computing techniques for Biology, Neuroscience and Knowledge Graph
        - An eye opening experience for personal development
    - "bachelor":
      school: "**Singapore Management Univeristy** (Bachelor of Science)"
      year: "Sep 2020 - May 2024"
      degree: "*Computer Science (AI and Marketing Analytics)*"
      description: |
        - ASEAN Undegraduate Scholars
        - Dean's List: AY 2021-2022, AY 2022-2023
  technology_stack:
    description: |
      - 👩‍💻 **Programming Languages**: Python, Java, Javascript, Solidity
      - 🗄️ **Web Frameworks**: Flask, Springboot
      - 🔧 **DevOps**: Ansible, Terraform
      - 🤖 **AI Frameworks**: PyTorch, Tensorflow
      - ☁️ **Cloud Services**: AWS, GCP
      - 📊 **Data Analytics**: Tableau, Excel, SQL, Streamlit
  work_experience:
    - "Doctor Anywhere":
      job: "**Data Engineer**"
      duration: "May 2023 - Aug 2023"
      company: "*Doctor Anywhere (Internship)*"
      description: |
        - Maintained CDC, Batch and Streaming ETL pipelines with MySQL, AWS DMS, Apache Beam, Kafka, GCP Big Query, GCP Data Flow, Ansible.
        - Implemented event-driven ETL pipelines using GCP Cloud Function, Cloud Run, PubSub, GCS.
        - Prototyped in-house chatbot to address data-related queries, with analytic feedback using Langchain, Langfuse, Chainlit, ChromaDB and VertexAI.
        - Refactored codebase and improved test coverage.
        - Implemented RPA for 3rd party UI integration and data scraping with Selenium.
    - "Grab":
      job: "**Academic Researcher • Operations External Talent**"
      duration: "Jan 2023 - May 2023"
      company: "*Grab (Apprenticeship)*"
      description: |
        - Implemented web-scraping microservice to retrieve Singapore's health institutions data with Flask, Selenium and Docker.
        - Developed and deployed binary classification model for validating medical certificates with Tensorflow.
        - Integrate OCR solution to automate medical certificates processing using AWS services (Lambda, ECS, Google Cloud APIs).
        - Implemented MLOps pipeline with MLflow (model registry) and Label Studio (auto mage labelling) that retrain deep learning model automatically to reduce model drift.
    - "SMU":
      job: "**Machine Learning Researcher**"
      duration: "May 2022 - Dec 2022"
      company: "*SMU Research Lab (Internship)*"
      description: |
        - Maintained AP-Coach Programming services using Docker and multiple AWS services (EC2, ECS, CodeCommit, CodePipeline, S3, Route53, RDS, Redis).
        - Full-stack web-app development with Flask back-end and HTML/CSS/JS & jQuery for front-end.
        - Enhanced code similarity check by implementing AST tree.
        - Enhanced code feedback mechanism (code hinting for programming beginners using OpenAI).
        - Reduced programming exercise creation time for instructors using Codex.
        - Developed new feature that can auto-generate coding exercises and test cases.
        - Improved coding questions feedback by integrating GPT-3 Python-code translation.
    - "Homebase":
      job: "**Data Engineer**"
      duration: "Jun 2022 - Nov 2022"
      company: "*Homebase (Internship)*"
      description: |
        - Implemented Facebook spamming tool to increase sales leads using Flask, Redis, jQuery, Heroku.
        - Automated Sales and HR metric collection to reduce reporting time for BI analyst with Google App Scripts.
        - Prototyped numerous automation tasks for Operation team using Python.
    - "Wiziin":
      job: "**Marketing Investment**"
      duration: "Jun 2021 - Aug 2021"
      company: "*Wiziin Inc (Internship)*"
      description: |
        - Conducted market research on regional and global startups investment platforms.
        - Translated and produced industry/startups-related written content on Vietnam Venture Capital Community Facebook and LinkedIn group.
        - Sourced, analyzed pitch decks and produced startups/SMEs-related content for Wiziin Beta platform.
Projects:
  "Text2SQL":
    project_name: "Text2SQL"
    image_path: "/Text2SQL.png"
    description: |
      An LLM-powered Chatbot that can generates semantically correct SQL queries given an user prompt, DDL schema and some sample csv data
      Leveraged Langchain to build prompts and integrate with LLMs such as VertexAI-Codechat and OpenAI GPT-3.5.
      Implemented text embeddings storage using ChromaDB vector database for targeted LLM relevant document queries.
      Implemented a lightweight chatbot UI using Chainlit that displays step-by-step how the LLMs generate responses.
      Integrated with Langfuse for LLM usage analytics and response evaluation.
    repo_link: "https://github.com/Dev317/Chainlit-Text2SQL"
    repo_name: "Dev317/Chainlit-Text2SQL"
    tech_stack: "Langchain, Chainlit, Langfuse, ChromaDB"
  "Audio Diffuser":
    project_name: "Audio Diffuser"
    image_path: "/AudioDiffuser.png"
    description: |
      An audio-thumbnail generator that leverages stable diffusion to convert sound to images.
      Assembling different pretrained models (VAE, UNet, VIT, AST) to create a stable diffusion system that generates images from text prompt.
      Created multilabeled classification model to classify sound types.
      Implemented a lightweight Flask server to serve the models.
    repo_link: "https://github.com/Dev317/Stable-Diffusion"
    repo_name: "Dev317/Stable-Diffusion"
    tech_stack: "Flask, PyTorch, AWS"
  "Wafflert":
    project_name: "Wafflert"
    image_path: "/Wafflert.jpeg"
    description: |
      A microservice-based, message driven app to order Triplet Waffle!
      Implemented Telegram-registration and messaging containerised microservices with Flask, Docker and RabbitMQ Architected application on AWS ECS with Terraform.
      Implemented CI/CD pipeline on GitLab that accelerates release of Docker images and auto deployment of Docker container
    repo_link: "https://github.com/Dev317/Wafflert"
    repo_name: "Dev317/Wafflert"
    tech_stack: "Flask, Express.js, Django, Terraform, AMQP, NGINX, Terraform"
  "Ascenda":
    project_name: "Ascenda"
    image_path: "/Ascenda.jpg"
    description: |
      A serverless-based app that processes 1GB credit card transactions a day.
      Developed a RESTful API backend system using AWS Lambda and API Gateway, processing 1GB of transaction data in less than 4 minutes.
      Implemented a high availability cloud architecture that can failover with Terraform.
      Implemented CI/CD pipeline on Github Actions, produced test cases for unit and integration testing.
    repo_link: "https://github.com/Dev317/AscendaTransactionApp"
    repo_name: "Dev317/AscendaTransactionApp"
    tech_stack: "AWS, React.js, NGINX, Terraform"
  "AP Coach":
    project_name: "AP Coach"
    image_path: "/APCoach.png"
    description: |
      An AI-based formative feedback generation to improve student learning outcomes in introductory programming courses.
      Integrated with GPT-3.5 to automate coding exercises, coding solutions and code explanations generation for Python language.
      Employed microservice-based approached to handle multiple services: user authentication, exercise generating and scoring.
    repo_link: "https://github.com/roystonlek/urpdevrepo"
    repo_name: "roystonlek/urpdevrepo"
    tech_stack: "Flask, jQuery, AWS, MySQL"
  "Jio Leh":
    project_name: "Jio Leh"
    image_path: "/JioLeh.png"
    description: |
      A Web3 social food discovery referral web-app.
      Developed a full-stack web-responsive Sanity and React.js app where users can post food content and F&B vendors can create promotional campaign.
      Designed, tested and deployed Ethereum smart contracts for managing payment system.
    repo_link: "https://github.com/Dev317/jioleh"
    repo_name: "Dev317/jioleh"
    tech_stack: "Sanity.io, React.js, Hardhat.js"
  "Fractionalise Housing":
    project_name: "Fractionalise Housing"
    image_path: "/FractionaliseHousing.png"
    description: |
      A fractionalised property platform to increase client's trust using Ethereum Blockchain.
      Developed a full-stack DApp with Next.js, deployed front-end with Vercel.
      Designed, tested and deployed Ethereum smart contracts for managing NFT listings, payments and escrow.
    repo_link: "https://github.com/Dev317/fractionalize-nft"
    repo_name: "Dev317/fractionalize-nft"
    tech_stack: "Next.js, Hardhat.js, Solidity"